on: push
jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3.0.0
      - name: 'build and deploy'
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          PAGES_BRANCH: master
          BUILD_DIR: .
          TOKEN: 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
          REPOSITORY: dantesingleton/dantesingleton.github.io